import sharp from "sharp";
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

// Prints public/logo.svg as a character grid, the way neofetch prints a distro logo, for the
// Skills section's fetch readout. The disc is filled with "netoun"; the squiggle stays hollow.
//
// Doto and the system monospace both advance 0.6em per glyph, so at `line-height: 1` a cell is
// 0.6 × 1: ROWS = COLS × 0.6 keeps the disc round.

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SOURCE = resolve(ROOT, "public/logo.svg");
const OUTPUT = resolve(ROOT, "app/features/skills/data/logo-ascii.ts");

const COLS = 42;
const ROWS = Math.round(COLS * 0.6);
const FILL = "netoun";
// Pixels sampled per cell, in the same 0.6 ratio.
const CELL_WIDTH = 12;
const CELL_HEIGHT = 20;
// Coverage thresholds: a full cell prints a letter, the edges fade to `:` then `.`.
const FULL = 0.62;
const EDGE = 0.3;
const FRINGE = 0.1;

const svg = readFileSync(SOURCE, "utf8");
const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
const path = svg.match(/\sd="([^"]+)"/)?.[1];
if (!viewBox || !path) throw new Error(`${SOURCE}: no viewBox or path to rasterise`);

// The logo's own fill rule hollows the squiggle out of the disc: white shape on black.
const mask = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${COLS * CELL_WIDTH}" height="${ROWS * CELL_HEIGHT}" preserveAspectRatio="none"><rect x="-1" y="-1" width="1000" height="1000" fill="black"/><path d="${path}" fill="white"/></svg>`;

const { data, info } = await sharp(Buffer.from(mask))
  .flatten({ background: "#000" })
  .greyscale()
  .raw()
  .toBuffer({ resolveWithObject: true });

const coverage = (col: number, row: number) => {
  let sum = 0;
  for (let y = 0; y < CELL_HEIGHT; y += 1) {
    for (let x = 0; x < CELL_WIDTH; x += 1) {
      const pixel = (row * CELL_HEIGHT + y) * info.width + (col * CELL_WIDTH + x);
      sum += data[pixel * info.channels];
    }
  }
  return sum / (CELL_WIDTH * CELL_HEIGHT * 255);
};

let letter = 0;
const lines = Array.from({ length: ROWS }, (_, row) => {
  let line = "";
  for (let col = 0; col < COLS; col += 1) {
    const value = coverage(col, row);
    if (value > FULL) line += FILL[letter++ % FILL.length];
    else if (value > EDGE) line += ":";
    else if (value > FRINGE) line += ".";
    else line += " ";
  }
  return line.trimEnd();
});

writeFileSync(
  OUTPUT,
  `// Generated by \`bun run generate-logo-ascii\` from public/logo.svg: do not edit by hand.
// ${COLS} × ${ROWS} cells of 0.6em × 1em (Doto's advance), so the disc prints round.
export const LOGO_ASCII = [
${lines.map((line) => `  ${JSON.stringify(line)},`).join("\n")}
];
`,
);

console.log(`✅ ${OUTPUT.replace(`${ROOT}/`, "")} (${COLS} × ${ROWS})`);
// sharp's worker pool can keep the process alive once the file is written.
process.exit(0);
